### ISSUE TITLE
Error using read_style

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [DeepSpace2/StyleFrame#37]
Hi!

I am struggling to get my simple piece of code working(I want to read the style from the excel):

```
from StyleFrame import StyleFrame, utils

sf = StyleFrame.read_excel('sss.xlsx',read_style=True, sheetname='Documents' )
print(sf)
```
This results in the following error:
```
Traceback (most recent call last):
  File "merge_excel4.py", line 3, in <module>
    sf = StyleFrame.read_excel('sss.xlsx',read_style=True, sheetname='Documents' )
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 178, in read_excel
    _read_style()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 154, in _read_style
    theme_colors = _get_scheme_colors_from_excel(wb)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 138, in _get_scheme_colors_from_excel
    root = fromstring(wb.loaded_theme)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\xml\etree\ElementTree.py", line 1314, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'
```

However removing `read_style=True` it runs just fine. Any ideas?

openpyxl = 2.2.5
pandas = 0.22.0
python = 3.6.6 64 bit
StyleFrame = 1.5

**Comment by DeepSpace2** [comment]
Hi there!
Well, that's.. interesting. Apparently openpyxl's `wb.loaded_theme` can be `None` even *after* the workbook is loaded. Didn't see this one coming :)

I'll release a "hot-fix" version in the next few minutes, will keep you posted.

**Comment by DeepSpace2** [comment]
@kristiansvenssonwsp Is it possible for you to share the Excel file? **I'm not interested in the data**, only the styling, so even a sheet with a dummy data will do. Thanks!

**Comment by kristiansvenssonwsp** [comment]
No problem. I attached two files that have the same problem, different sheet names though.
[compare_excel_pdf.xlsx](https://github.com/DeepSpace2/StyleFrame/files/2168032/compare_excel_pdf.xlsx)
[sss.xlsx](https://github.com/DeepSpace2/StyleFrame/files/2168033/sss.xlsx)

**Comment by kristiansvenssonwsp** [comment]
Thanks, super quick response! It seems to work nicely now. 

I got another problem, probaly not related to this issue. 
Using read_excel from pandas I can use sheetname=0 (integer, not string) to read the first sheet in the excel file. Doing the same with StyleFrame I get this error:

```
C:\Users\krill\AppData\Local\Programs\Python\Python36\Scripts>python merge_excel3.py
C:\\Users\\krill\\Downloads\\xlsx\compare_excel_pdf.xlsx
C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\util\_decorators.py:118: FutureWarning:The `sheetname` keyword is deprecated, use `sheet_name` instead
Traceback (most recent call last):
  File "merge_excel3.py", line 25, in <module>
    data = StyleFrame.read_excel(spreadsheet, read_style=True, sheetname=0)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 180, in read_excel
    _read_style()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 155, in _read_style
    sheet = wb.get_sheet_by_name(sheetname)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\workbook\workbook.py", line 214, in get_sheet_by_name
    return self[name]
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\workbook\workbook.py", line 233, in __getitem__
    raise KeyError("Worksheet {0} does not exist.".format(key))
KeyError: 'Worksheet 0 does not exist.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "merge_excel3.py", line 45, in <module>
    df1[num].to_excel(writer, index=False, sheet_name = df1Snames[num])
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\excel.py", line 824, in __exit__
    self.close()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\excel.py", line 828, in close
    return self.save()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\excel.py", line 862, in save
    return self.book.save(self.path)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\workbook\workbook.py", line 298, in save
    save_workbook(self, filename)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\writer\excel.py", line 198, in save_workbook
    writer.save(filename, as_template=as_template)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\writer\excel.py", line 181, in save
    self.write_data(archive, as_template=as_template)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\writer\excel.py", line 67, in write_data
    archive.writestr(ARC_WORKBOOK_RELS, write_workbook_rels(self.workbook))
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\writer\workbook.py", line 321, in write_workbook_rels
    i += 1
UnboundLocalError: local variable 'i' referenced before assignment
```

Should I start a new issue for this?
