### ISSUE TITLE
Using integer in sheetname

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [DeepSpace2/StyleFrame#38]
Using read_excel from pandas I can use sheetname=0 (integer, not string) to read the first sheet in the excel file. Doing the same with StyleFrame I get this error:

```
C:\Users\krill\AppData\Local\Programs\Python\Python36\Scripts>python merge_excel3.py
C:\\Users\\krill\\Downloads\\xlsx\compare_excel_pdf.xlsx
C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\util\_decorators.py:118: FutureWarning:The `sheetname` keyword is deprecated, use `sheet_name` instead
Traceback (most recent call last):
  File "merge_excel3.py", line 25, in <module>
    data = StyleFrame.read_excel(spreadsheet, read_style=True, sheetname=0)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 180, in read_excel
    _read_style()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 155, in _read_style
    sheet = wb.get_sheet_by_name(sheetname)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\workbook\workbook.py", line 214, in get_sheet_by_name
    return self[name]
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\workbook\workbook.py", line 233, in __getitem__
    raise KeyError("Worksheet {0} does not exist.".format(key))
KeyError: 'Worksheet 0 does not exist.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "merge_excel3.py", line 45, in <module>
    df1[num].to_excel(writer, index=False, sheet_name = df1Snames[num])
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\excel.py", line 824, in __exit__
    self.close()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\excel.py", line 828, in close
    return self.save()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\excel.py", line 862, in save
    return self.book.save(self.path)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\workbook\workbook.py", line 298, in save
    save_workbook(self, filename)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\writer\excel.py", line 198, in save_workbook
    writer.save(filename, as_template=as_template)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\writer\excel.py", line 181, in save
    self.write_data(archive, as_template=as_template)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\writer\excel.py", line 67, in write_data
    archive.writestr(ARC_WORKBOOK_RELS, write_workbook_rels(self.workbook))
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\writer\workbook.py", line 321, in write_workbook_rels
    i += 1
UnboundLocalError: local variable 'i' referenced before assignment
```
openpyxl = 2.2.5
pandas = 0.22.0
python = 3.6.6 64 bit
StyleFrame = 1.5.1

**Comment by DeepSpace2** [comment]
For the record, this happens only when using `read_style=True`.  If `read_style` is not used then `sheetname=0` will read the 1<sup>st</sup> sheet as expected (however a decent IDE will show a warning because the type `str` is used in the docstring)

**Comment by DeepSpace2** [comment]
As the milestone suggests I plan to add this to 1.6, but if you feel comfortable you can modify your local file: `style_frame.py`, change line 157 (`sheet = wb.get_sheet_by_name(sheet_name)`) to:

```python
            if isinstance(sheet_name, str):
                sheet = wb.get_sheet_by_name(sheet_name)
            elif isinstance(sheet_name, int):
                sheet = wb.worksheets[sheet_name]
```

Keep in mind that this still won't provide support for a list of sheet names like `pandas.read_excel`.

**Comment by kristiansvenssonwsp** [comment]
Wow, thanks! I works fine for my purpose. I´ll make sure to keep an eye out for the next release.
