### ISSUE TITLE
read_excel Problematic file

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [DeepSpace2/StyleFrame#39]
I encountered a problematic excel file. The file is attached.

Using this code:

```
from StyleFrame import StyleFrame, utils

sf = StyleFrame.read_excel('AU_017_Planning.xlsx',read_style=True, sheetname='Sheet1' )
print(sf)
```

I get this error:
```
C:\Users\krill\AppData\Local\Programs\Python\Python36\Scripts>python merge_excel4.py
C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\util\_decorators.py:118: FutureWarning:The `sheetname` keyword is deprecated, use `sheet_name` instead
Traceback (most recent call last):
  File "merge_excel4.py", line 3, in <module>
    sf = StyleFrame.read_excel('AU_017_Planning.xlsx',read_style=True, sheetname='Sheet1' )
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 184, in read_excel
    _read_style()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\StyleFrame\style_frame.py", line 154, in _read_style
    wb = load_workbook(path)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\reader\excel.py", line 149, in load_workbook
    _load_workbook(wb, archive, filename, read_only, keep_vba)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\reader\excel.py", line 236, in _load_workbook
    color_index=wb._colors)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\reader\worksheet.py", line 327, in read_worksheet
    fast_parse(ws, xml_source, shared_strings, style_table, color_index)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\reader\worksheet.py", line 315, in fast_parse
    parser.parse()
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\reader\worksheet.py", line 94, in parse
    dispatcher[tag_name](element)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\reader\worksheet.py", line 310, in parse_sheet_views
    self.ws.sheet_view = SheetView.from_tree(el)
  File "C:\Users\krill\AppData\Local\Programs\Python\Python36\lib\site-packages\openpyxl\descriptors\serialisable.py", line 52, in from_tree
    return cls(**attrib)
TypeError: __init__() got an unexpected keyword argument '{http://schemas.microsoft.com/office/spreadsheetml/2016/revision3}uid'
```

openpyxl = 2.2.5
pandas = 0.22.0
python = 3.6.6 64 bit
StyleFrame = 1.5.1

[AU_017_Planning.xlsx](https://github.com/DeepSpace2/StyleFrame/files/2168437/AU_017_Planning.xlsx)

**Comment by DeepSpace2** [comment]
This is an openpyxl issue:

```python
import openpyxl
    
wb = openpyxl.load_workbook('AU_017_Planning.xlsx')

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    wb = openpyxl.load_workbook('AU_017_Planning.xlsx')
  File "D:\Python36\lib\site-packages\openpyxl\reader\excel.py", line 149, in load_workbook
    _load_workbook(wb, archive, filename, read_only, keep_vba)
  File "D:\Python36\lib\site-packages\openpyxl\reader\excel.py", line 236, in _load_workbook
    color_index=wb._colors)
  File "D:\Python36\lib\site-packages\openpyxl\reader\worksheet.py", line 327, in read_worksheet
    fast_parse(ws, xml_source, shared_strings, style_table, color_index)
  File "D:\Python36\lib\site-packages\openpyxl\reader\worksheet.py", line 315, in fast_parse
    parser.parse()
  File "D:\Python36\lib\site-packages\openpyxl\reader\worksheet.py", line 94, in parse
    dispatcher[tag_name](element)
  File "D:\Python36\lib\site-packages\openpyxl\reader\worksheet.py", line 310, in parse_sheet_views
    self.ws.sheet_view = SheetView.from_tree(el)
  File "D:\Python36\lib\site-packages\openpyxl\descriptors\serialisable.py", line 52, in from_tree
    return cls(**attrib)
TypeError: __init__() got an unexpected keyword argument '{http://schemas.microsoft.com/office/spreadsheetml/2016/revision3}uid'
```
