### ISSUE TITLE
Internal imports are broken

### ISSUE THREAD

**Issue by lyssdod** [DeepSpace2/StyleFrame#71]
Hi, I guess due to https://github.com/DeepSpace2/StyleFrame/issues/68 some internal imports are broken:

```
pip install styleframe

...

>>> import styleframe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'styleframe'
>>> import StyleFrame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'styleframe'
>>> from StyleFrame import StyleFrame, Styler, utils   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.7/site-packages/StyleFrame/__init__.py", line 3, in <module>
    from .container import Container
  File "/lib/python3.7/site-packages/StyleFrame/container.py", line 6, in <module>
    from styleframe.styler import Styler
ModuleNotFoundError: No module named 'styleframe'
```

I think it's because of https://github.com/DeepSpace2/StyleFrame/blob/master/setup.py#L27 , which makes module available under that name

**Comment by DeepSpace2** [comment]
Hi. Yeah, I found about this issue too late. Funny enough, all the [Travis builds are still passing. ](https://travis-ci.org/github/DeepSpace2/StyleFrame/builds/696495513)

The problem seems to persist even after changing https://github.com/DeepSpace2/StyleFrame/blob/97a1b0b2930723e6f8134e13b4159f89489c33e5/setup.py#L27 to `name='styleframe'`.

I'll continue to investigate, meanwhile I'm taking 3.0.0 down.
Sorry @impredicative ;)

**Comment by DeepSpace2** [comment]
I narrowed down the problem, `python setup.py bdist_wheel` still builds the `.whl` with the old, capitalized paths:

```
(styleframe-yfuZ6KlP) λ python setup.py bdist_wheel
Warning: 'keywords' should be a list, got type 'tuple'
running bdist_wheel
running build
running build_py
running egg_info
writing styleframe.egg-info\PKG-INFO
writing dependency_links to styleframe.egg-info\dependency_links.txt
writing entry points to styleframe.egg-info\entry_points.txt
writing requirements to styleframe.egg-info\requires.txt
writing top-level names to styleframe.egg-info\top_level.txt
reading manifest file 'styleframe.egg-info\SOURCES.txt'
writing manifest file 'styleframe.egg-info\SOURCES.txt'
warning: build_py: byte-compiling is disabled, skipping.

installing to build\bdist.win-amd64\wheel
running install
running install_lib
creating build\bdist.win-amd64\wheel
creating build\bdist.win-amd64\wheel\StyleFrame
creating build\bdist.win-amd64\wheel\StyleFrame\command_line
copying build\lib\StyleFrame\command_line\commandline.py -> build\bdist.win-amd64\wheel\.\StyleFrame\command_line
creating build\bdist.win-amd64\wheel\StyleFrame\command_line\tests
copying build\lib\StyleFrame\command_line\tests\commandline_tests.py -> build\bdist.win-amd64\wheel\.\StyleFrame\command_line\tests
copying build\lib\StyleFrame\command_line\tests\json_schema.py -> build\bdist.win-amd64\wheel\.\StyleFrame\command_line\tests
copying build\lib\StyleFrame\command_line\tests\test_json.json -> build\bdist.win-amd64\wheel\.\StyleFrame\command_line\tests
copying build\lib\StyleFrame\command_line\tests\test_json_string.json -> build\bdist.win-amd64\wheel\.\StyleFrame\command_line\tests
copying build\lib\StyleFrame\command_line\tests\__init__.py -> build\bdist.win-amd64\wheel\.\StyleFrame\command_line\tests
copying build\lib\StyleFrame\command_line\__init__.py -> build\bdist.win-amd64\wheel\.\StyleFrame\command_line
copying build\lib\StyleFrame\container.py -> build\bdist.win-amd64\wheel\.\StyleFrame
copying build\lib\StyleFrame\deprecations.py -> build\bdist.win-amd64\wheel\.\StyleFrame
copying build\lib\StyleFrame\series.py -> build\bdist.win-amd64\wheel\.\StyleFrame
copying build\lib\StyleFrame\styler.py -> build\bdist.win-amd64\wheel\.\StyleFrame
copying build\lib\StyleFrame\style_frame.py -> build\bdist.win-amd64\wheel\.\StyleFrame
creating build\bdist.win-amd64\wheel\StyleFrame\tests
copying build\lib\StyleFrame\tests\container_tests.py -> build\bdist.win-amd64\wheel\.\StyleFrame\tests
copying build\lib\StyleFrame\tests\series_tests.py -> build\bdist.win-amd64\wheel\.\StyleFrame\tests
copying build\lib\StyleFrame\tests\styler_tests.py -> build\bdist.win-amd64\wheel\.\StyleFrame\tests
copying build\lib\StyleFrame\tests\style_frame_tests.py -> build\bdist.win-amd64\wheel\.\StyleFrame\tests
copying build\lib\StyleFrame\tests\tests.py -> build\bdist.win-amd64\wheel\.\StyleFrame\tests
copying build\lib\StyleFrame\tests\__init__.py -> build\bdist.win-amd64\wheel\.\StyleFrame\tests
copying build\lib\StyleFrame\utils.py -> build\bdist.win-amd64\wheel\.\StyleFrame
copying build\lib\StyleFrame\version.py -> build\bdist.win-amd64\wheel\.\StyleFrame
copying build\lib\StyleFrame\__init__.py -> build\bdist.win-amd64\wheel\.\StyleFrame
warning: install_lib: byte-compiling is disabled, skipping.

running install_egg_info
Copying styleframe.egg-info to build\bdist.win-amd64\wheel\.\styleframe-3.0.0-py3.7.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build\bdist.win-amd64\wheel\styleframe-3.0.0.dist-info\WHEEL
creating 'dist\styleframe-3.0.0-py3-none-any.whl' and adding 'build\bdist.win-amd64\wheel' to it
adding 'StyleFrame/__init__.py'
adding 'StyleFrame/container.py'
adding 'StyleFrame/deprecations.py'
adding 'StyleFrame/series.py'
adding 'StyleFrame/style_frame.py'
adding 'StyleFrame/styler.py'
adding 'StyleFrame/utils.py'
adding 'StyleFrame/version.py'
adding 'StyleFrame/command_line/__init__.py'
adding 'StyleFrame/command_line/commandline.py'
adding 'StyleFrame/command_line/tests/__init__.py'
adding 'StyleFrame/command_line/tests/commandline_tests.py'
adding 'StyleFrame/command_line/tests/json_schema.py'
adding 'StyleFrame/command_line/tests/test_json.json'
adding 'StyleFrame/command_line/tests/test_json_string.json'
adding 'StyleFrame/tests/__init__.py'
adding 'StyleFrame/tests/container_tests.py'
adding 'StyleFrame/tests/series_tests.py'
adding 'StyleFrame/tests/style_frame_tests.py'
adding 'StyleFrame/tests/styler_tests.py'
adding 'StyleFrame/tests/tests.py'
adding 'styleframe-3.0.0.dist-info/LICENSE'
adding 'styleframe-3.0.0.dist-info/METADATA'
adding 'styleframe-3.0.0.dist-info/WHEEL'
adding 'styleframe-3.0.0.dist-info/entry_points.txt'
adding 'styleframe-3.0.0.dist-info/top_level.txt'
adding 'styleframe-3.0.0.dist-info/RECORD'
removing build\bdist.win-amd64\wheel
```

Still not sure why though.

**Comment by lyssdod** [comment]
thank you @DeepSpace2 ! :)
